In [3]:
import numpy as np

In [4]:
nums = [1, 2, 3]

In [5]:
# creating arrays in numpy
nums = np.array(nums)

In [6]:
nums

array([1, 2, 3])

In [7]:
# creating 2D arrays in numpy
nums = [[1,2,3], [4,5,6]]

In [8]:
nums = np.array(nums)

In [9]:
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# checking dimension of array
nums.ndim

2

In [11]:
# returns a tuple containing (rows, cols)
nums.shape

(2, 3)

# Data Type
you can only store one data type in numpy arrays as oppose to python array in which you can store multiple data types. This is the reason numpy arrays are very fast as compared to python lists.

In [12]:
# checking data type
nums.dtype

dtype('int32')

In [13]:
# after changing one value to float the entire array data type changes to float
nums = np.array([1, 2.2, 3])

In [14]:
nums.dtype

dtype('float64')

In [15]:
# after changing one value to string the entire array data type changes to string
nums = np.array([1, '2', 3])

In [16]:
nums.dtype

dtype('<U11')

# zeros method 

In [17]:
# zeroes method in numpy initializes an array with zeroes
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [18]:
# passing a tuple of (rows, cols)
arr = np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

# ones method

In [19]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

# eye method

In [20]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# diag method 

In [22]:
arr = np.diag([1,2,3,4])
arr

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
# can also use it this way to find diagonal elements of matrix
np.diag(arr)

array([1, 2, 3, 4])

# randint method 

In [24]:
# random.randint(a, b, c)
# generate c random numbers between a and b where a is inclusive but b is exclusive
rand_arr = np.random.randint(1, 15, 4);
rand_arr

array([13, 10,  5,  1])

# rand method 

In [25]:
# random.rand(n)
# generate n random numbers between 1 and 0
rand_arr = np.random.rand(4)
rand_arr

array([0.86380914, 0.53494703, 0.91594588, 0.83251308])

In [26]:
# generating elements in 2D array
rand_arr = np.random.rand(2,3)
rand_arr

array([[0.4531802 , 0.47246255, 0.62540775],
       [0.75440284, 0.24224995, 0.27433865]])

# randn method 

In [27]:
# random numbers that are centered around 0
# i.e : having mean around 0
# numbers generated are from standard normal distribution
rand_arr = np.random.randn(4)
rand_arr

array([ 1.39824815, -1.10254506, -0.05448008, -1.07148728])

In [28]:
np.mean(rand_arr)

-0.20756606796782046

# reshaping data 

In [29]:
arr = np.random.randint(1,100,20)
arr

array([87, 80,  1, 77, 52, 41, 54, 45, 26, 93, 26, 60, 50, 92,  9, 94, 33,
       53, 32, 28])

In [30]:
arr.shape

(20,)

In [31]:
# reshaping means converting 1D array to 2D or 3D, or 2D to 1D etc
# arr.reshape(rows, cols)
# arr.reshape(a, b)
# where a*b must be equal to size of original array
# i.e : in above example take a = 2, b = 10
# 2 * 10 = 20 which is size of original array

In [32]:
arr = arr.reshape(2, 10)
arr

array([[87, 80,  1, 77, 52, 41, 54, 45, 26, 93],
       [26, 60, 50, 92,  9, 94, 33, 53, 32, 28]])

In [33]:
arr.shape

(2, 10)

In [34]:
arr.ndim

2

In [35]:
# changing back to original dimesions
arr = arr.reshape(20)
arr

array([87, 80,  1, 77, 52, 41, 54, 45, 26, 93, 26, 60, 50, 92,  9, 94, 33,
       53, 32, 28])

In [36]:
# can also reshape in 3D
arr = arr.reshape(2, 2, 5)
arr

array([[[87, 80,  1, 77, 52],
        [41, 54, 45, 26, 93]],

       [[26, 60, 50, 92,  9],
        [94, 33, 53, 32, 28]]])

# arrange method

In [37]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# -1 in reshape

In [39]:
# arr.reshape(2, -1)
# if second argument is -1 then numpy automatically calculates the second argument on its own
# i.e : in above example since total elements are 10, second argument will be 5
arr.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
arr.reshape(5, -1)
# in this case second argument will be 2

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [41]:
# we can also use it this way
arr.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# seed function
generating same random numbers

In [48]:
# this is will generate same random numbers everytime on any device
np.random.seed(12)
arr = np.random.randint(1,101,10)
arr

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

# size of array 

In [45]:
arr.size

10

# indexing and slicing 

In [47]:
# indexing in 1D array in numpy is same as python lists
arr[0]

76

In [50]:
arr[-1]

50

In [51]:
# slicing is also same
arr[0:3]

array([76, 28,  7])

In [52]:
arr[1:]

array([28,  7,  3,  4, 68, 77, 49, 23, 50])

In [53]:
arr[:2]

array([76, 28])

In [54]:
arr[:]

array([76, 28,  7,  3,  4, 68, 77, 49, 23, 50])

In [55]:
# arr[start:stop:step]
arr[1:5:2]

array([28,  3])

In [56]:
# reversing array
arr[::-1]

array([50, 23, 49, 77, 68,  4,  3,  7, 28, 76])

In [58]:
# indexing in 2D array
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])
matrix

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [59]:
# indexing using double bracket notation
matrix[0][1]

10

In [60]:
# indexing using single bracket notation (recommended)
matrix[0,1]

10

In [61]:
# slicing using single bracket notation
# matrix[range for rows, range for columns]
matrix[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [62]:
matrix[:2, :2]

array([[ 5, 10],
       [20, 25]])

In [63]:
matrix[1:, 1:]

array([[25, 30],
       [40, 45]])